### PR TITLE
Add note about passphrases and ssh-keygen on macOS.

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Comment by dhermes** [comment]
FWIW the [current][1] code that does the key decryption could be updated to accommodate the `BEGIN OPENSSH PRIVATE KEY` format.

[1]: https://github.com/mdsol/docker-ssh-exec/blob/7e6505482c95cf17d632be5c156a412a4d063a43/server.go#L64

**Comment by dhermes** [comment]
@benton Gentle nudge.

**Review by benton — APPROVED** [review]
Thank you!

**Comment by dhermes** [comment]
Thank you for this great tool. Cheers!

**Pull request merged**
